---
# ARZENS Week 06-07 Combined Assignment - Task 6: Ansible Roles
# File: roles/common/handlers/main.yml

- name: restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
